
import React, { useState, useEffect } from 'react';
import { ViewMode } from '../types';

interface TourProps {
  onClose: () => void;
  onNavigate: (view: ViewMode) => void;
  onStepChange?: (view: ViewMode) => void;
}

const steps = [
  {
    title: "Welcome to the Studio",
    content: "This is the CarDetailing.PL workshop experience. We focus on high-end automotive preservation in Poznań.",
    commandLabel: "Stay on Home",
    view: ViewMode.HOME
  },
  {
    title: "AI Detailing Advisor",
    content: "Test our Gemini-powered advisor. It can diagnose paint issues, suggest protection plans, and even speak to you using TTS.",
    commandLabel: "Enter Advisor",
    view: ViewMode.ADVISOR
  },
  {
    title: "Finish Visualizer",
    content: "Wondering how a ceramic coating looks on your Porsche? Our generative visualizer creates studio-quality renders with PL plates.",
    commandLabel: "Launch Visualizer",
    view: ViewMode.VISUALIZER
  },
  {
    title: "Concierge Booking",
    content: "Select your signature services and get a personalized restoration strategy generated by AI upon submission.",
    commandLabel: "Start Booking",
    view: ViewMode.BOOKING
  }
];

const Tour: React.FC<TourProps> = ({ onClose, onNavigate, onStepChange }) => {
  const [currentStep, setCurrentStep] = useState(0);

  const step = steps[currentStep];

  // Sync background view when currentStep changes
  useEffect(() => {
    if (onStepChange) {
      onStepChange(steps[currentStep].view);
    }
  }, [currentStep, onStepChange]);

  const handleNext = () => {
    const nextIdx = (currentStep + 1) % steps.length;
    setCurrentStep(nextIdx);
  };

  const handleCommand = () => {
    // Close the tour and stay on this tab
    onNavigate(step.view);
  };

  const handleGoHome = () => {
    // Specifically navigate home and close tour
    onNavigate(ViewMode.HOME);
  };

  const handleCloseModal = () => {
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-6 bg-[#05070a]/70 backdrop-blur-md animate-in fade-in duration-300">
      <div className="bg-[#080a0f] border border-blue-500/30 max-w-sm w-full rounded-[2.5rem] p-10 shadow-[0_0_50px_rgba(37,99,235,0.2)] relative overflow-hidden">
        {/* Progress Bar */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-white/5">
          <div 
            className="h-full bg-blue-500 transition-all duration-500 ease-out" 
            style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }}
          ></div>
        </div>

        <div className="flex items-center justify-between mb-8">
          <div className="flex flex-col">
            <span className="text-[10px] font-bold text-blue-500 uppercase tracking-[0.4em] mb-1">Studio Interface</span>
            <span className="text-[9px] font-mono text-slate-500 uppercase">Phase {currentStep + 1} / {steps.length}</span>
          </div>
          <button 
            onClick={handleCloseModal} 
            className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center text-slate-500 hover:text-white hover:bg-white/10 transition-all"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <h3 className="text-3xl font-display font-bold text-white mb-4 tracking-tight uppercase leading-tight">{step.title}</h3>
        <p className="text-slate-400 text-sm mb-10 leading-relaxed font-light italic opacity-90">
          "{step.content}"
        </p>

        <div className="flex flex-col gap-4">
          <button 
            onClick={handleCommand}
            className="w-full py-5 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl font-bold uppercase tracking-[0.3em] text-[10px] transition-all shadow-xl shadow-blue-500/30 flex items-center justify-center gap-3 group"
          >
            <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse"></span>
            {step.commandLabel}
          </button>
          
          <div className="flex gap-3">
             <button 
                onClick={handleNext}
                className="flex-1 py-4 bg-white/5 hover:bg-white/10 text-slate-300 rounded-2xl font-bold uppercase tracking-widest text-[9px] transition-all border border-white/10 flex items-center justify-center gap-2 group"
              >
                Next Slide
                <svg className="w-3 h-3 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M9 5l7 7-7 7" />
                </svg>
              </button>
              
              <button 
                onClick={handleGoHome}
                className="px-6 py-4 bg-transparent text-slate-600 hover:text-blue-500 font-bold uppercase tracking-widest text-[9px] transition-all flex items-center gap-2"
              >
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                </svg>
                Home
              </button>
          </div>
        </div>

        {/* Ambient background decoration */}
        <div className="absolute -bottom-20 -right-20 w-40 h-40 bg-blue-500/10 blur-[80px] rounded-full pointer-events-none"></div>
      </div>
    </div>
  );
};

export default Tour;
